# Generated by Django 4.2.1 on 2023-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_video_time_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(
                choices=[
                    ("ENGLISH", "ENGLISH"),
                    ("INDONESIA", "INDONESIA"),
                    ("ARABIC", "ARABIC"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
