# Generated by Django 4.2.1 on 2023-06-16 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_categories_jurusan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories_jurusan",
            name="icon",
        ),
    ]
