# Generated by Django 4.2.1 on 2023-06-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_categories_jurusan_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories_keterampilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
