# Generated by Django 4.2.1 on 2023-06-16 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_categories_keterampilan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course_school",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(null=True, upload_to="Media/featured_img"),
                ),
                ("featured_video", models.CharField(max_length=300, null=True)),
                ("title", models.CharField(max_length=500)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                ("price", models.IntegerField(default=0, null=True)),
                ("discount", models.IntegerField(null=True)),
                (
                    "slug",
                    models.SlugField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PUBLISH", "PUBLISH"), ("DRAFT", "DRAFT")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "ENGLISH"),
                            ("INDONESIA", "INDONESIA"),
                            ("ARABIC", "ARABIC"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.categories_jurusan",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.level",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course_keterampilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(null=True, upload_to="Media/featured_img"),
                ),
                ("featured_video", models.CharField(max_length=300, null=True)),
                ("title", models.CharField(max_length=500)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("description", models.TextField()),
                ("price", models.IntegerField(default=0, null=True)),
                ("discount", models.IntegerField(null=True)),
                (
                    "slug",
                    models.SlugField(blank=True, default="", max_length=500, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PUBLISH", "PUBLISH"), ("DRAFT", "DRAFT")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ENGLISH", "ENGLISH"),
                            ("INDONESIA", "INDONESIA"),
                            ("ARABIC", "ARABIC"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.author",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.categories_keterampilan",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.level",
                    ),
                ),
            ],
        ),
    ]
