# Generated by Django 4.2.1 on 2023-06-16 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_course_school_course_keterampilan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course_school",
            old_name="category",
            new_name="category_jur",
        ),
    ]
