# Generated by Django 4.2.1 on 2023-06-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_rename_author_course_school_author_jur_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="categories_jurusan",
            old_name="name",
            new_name="name_jur",
        ),
    ]
