# Generated by Django 4.2.1 on 2023-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_rename_name_categories_jurusan_name_jur"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
