# Generated by Django 4.2.1 on 2023-06-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_remove_usercourse_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
