# Generated by Django 4.2.1 on 2023-06-26 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_alter_course_price_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
    ]
