# Generated by Django 4.2.1 on 2023-06-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_lesson_course"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="course",
            new_name="course_id",
        ),
    ]
