# Generated by Django 4.2.1 on 2023-06-26 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0025_rename_course_id_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.course"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
