# Generated by Django 4.2.1 on 2023-06-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0026_alter_lesson_course_alter_lesson_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="youtube_url",
            field=models.URLField(null=True),
        ),
    ]
