# Generated by Django 4.2.1 on 2023-06-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_video_youtube_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="youtube_url",
        ),
    ]
