# Generated by Django 4.2.1 on 2023-07-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_payment_created_at_payment_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="verified",
        ),
    ]
