# Generated by Django 4.2.1 on 2023-07-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_remove_payment_verified"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercourse",
            old_name="date",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user_course",
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.order"
            ),
        ),
        migrations.AddField(
            model_name="usercourse",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
