# Generated by Django 4.2.1 on 2023-07-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_rename_date_usercourse_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
