# Generated by Django 4.2.1 on 2023-07-29 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_rename_status_payment_is_verified_payment_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course_school",
            name="author_jur",
        ),
        migrations.RemoveField(
            model_name="course_school",
            name="category_jur",
        ),
        migrations.RemoveField(
            model_name="course_school",
            name="level_jur",
        ),
        migrations.DeleteModel(
            name="Course_keterampilan",
        ),
        migrations.DeleteModel(
            name="Course_school",
        ),
    ]
