# Generated by Django 4.2.1 on 2023-07-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_remove_course_school_author_jur_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_profile",
            field=models.ImageField(upload_to="author/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="featured_image",
            field=models.ImageField(null=True, upload_to="featured_img/"),
        ),
        migrations.AlterField(
            model_name="video",
            name="thumbnail",
            field=models.ImageField(null=True, upload_to="Yt_Thumbnail/"),
        ),
    ]
