# Generated by Django 4.2.1 on 2023-07-30 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_delete_categories_jurusan_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="author_profile",
            new_name="image_author",
        ),
    ]
