# Generated by Django 4.2.1 on 2023-07-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_rename_author_profile_author_image_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="image_author",
            field=models.ImageField(null=True, upload_to="author/"),
        ),
    ]
