# Generated by Django 4.2.1 on 2023-07-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0041_uservideowatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercourse",
            name="watched_videos",
            field=models.ManyToManyField(blank=True, to="app.video"),
        ),
    ]
