# Generated by Django 4.2.1 on 2023-12-08 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sekolah", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Sma",
        ),
        migrations.RenameIndex(
            model_name="sma",
            new_name="sekolah_sma_publish_ae53cd_idx",
            old_name="sekolah_pos_publish_8ecfbd_idx",
        ),
    ]
