# Generated by Django 4.2.1 on 2023-12-24 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artikel", "0002_artikelpost_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artikelpost",
            name="category",
        ),
    ]
