# Generated by Django 4.2.1 on 2023-12-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artikel", "0003_remove_artikelpost_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikelpost",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artikel.categories",
            ),
        ),
    ]
